### ISSUE TITLE
Commander gets confused in double battle when one pokemon is fainted

### ISSUE THREAD

**Issue by tustin2121** [m4-used-rollout/commander-mode#11]
Clip: https://clips.twitch.tv/StrangePleasantElephantEagleEye

At the end of this double battle, Commander failed to understand that the first pokemon was fainted and so control went directly to the second pokemon. It was actually counter-productive, cancelling out of the Fight menu when `MOVE#` was used.

**Comment by m4-used-rollout** [comment]
Control only moved to tracking the second mon if the first mon was in the `PlayerHandleLinkStandbyMsg` state. Now Commander also accounts for the `PlayerHandleSpriteInvisibility` state, which is what a fainted doubles mon gets set to.
